[package]
name = "mqpf"
version = "0.1.1"
edition = "2021"
description = "Path renderer for macroquad based on pathfinder code"
license = "MIT"
repository = "https://github.com/birhburh/mqpf"

build = "build/main.rs"

[features]
svg = ["usvg"]
default = []

[[example]]
name = "tiger"
required-features = ["svg"]

[dependencies]
macroquad = { version = "=0.4.14" }
bitflags = "1.0"
pathfinder_geometry = "=0.5.1"
pathfinder_simd = "=0.5.4"
usvg = { version = "=0.44.0", optional = true }

[build-dependencies]
euclid = "0.20"
image = "0.23"

[package.metadata.android]
label = "MQPF EXAMPLE"
min_sdk_version = 26
target_sdk_version = 28
build_targets = ["aarch64-linux-android"]